code/cryptotradingsimulator/cryptotradingsimulator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from tradingplatform import views


urlpatterns = [
    path('', include('tradingplatform.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
]

code/cryptotradingsimulator/members/urls.py
from django.urls import path, include
from . import views

app_name = "members"
urlpatterns = [
    path('login_user', views.login_user, name="login"),
    path('logout_user', views.logout_user, name="logout"),
    path('register_user', views.register_user, name="register"),
]

code/cryptotradingsimulator/tradingplatform/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = "tradingplatform"
urlpatterns = [
    path('', views.index, name='index'),  # /app
    path('trade', views.trade, name='trade'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('following', views.following, name='following'),
]

code/cryptotradingsimulator/templates/balance.html
{% if user.is_authenticated %}
<button type="button" class="btn btn-light">Your Balance: ${% for user in platform_user %} {{ user.balance }} {% endfor %}</button>
{% endif %}

code/cryptotradingsimulator/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>CryptoSim</title>
  </head>

  <style>
      title {color: mediumpurple}
      body {background: lightgrey}
      body {font-family: Georgia}
      h1 {font-family: Tahoma}
      h2 {font-family: Tahoma}
  </style>
  <body>
{% load static %}
<link rel="stylesheet" type="text/css" href="static/stylesheet.css" />
  {% include 'navbar.html' %}
  <br/>

    <div class="container">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
    </div>
            {% endfor %}
        {% endif %}


        {% block content %}

        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block scripts %}

        {% endblock %}
  </body>


</html>

code/cryptotradingsimulator/templates/index.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}

<style>
      .footer {
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: #BEBEBE;
      color: white;
      text-align: center;
}
</style>

{% if user.is_authenticated %}

{% load static %}
<body>
<link rel="stylesheet" type="text/css" href="static/stylesheet.css" />

<h1>Dashboard</h1>
<hr/>

{% if new_user %}
<p>Hello, <b>{{ user.first_name }}</b>. Looks like you're new here.</p>
<p>We have given you $7000 to begin your cryptocurrency trading journey.</p>
<p>Why not head to the "Trade" page, and see if you can make an investment?</p>
{% else %}
<p>Hello <b>{{ user.first_name }}</b>, Welcome back to CryptoSim.</p>
{% endif %}

<div class="card" style="width: 25rem;">
  <div class="card-header">
    <b>{{ user.first_name }}'s Stats</b> {{ position.cryptocurrency }}
  </div>
  {% for user in platform_user %}
  <ul class="list-group list-group-flush">
    <li class="list-group-item">You have <b>{{ open_positions.count }}</b> open trades.</li>
      <li class="list-group-item">All-time PNL (USD): <b> {{ user.PNL|floatformat:2 }} </b></li>
      <li class="list-group-item">All-time ROI: <b>{{ user.ROI|floatformat:2 }}%</b></li>
    </ul>
  {% endfor %}

{% else %}
<h1>About Us...</h1>
<hr/>
<p>Hello, beginner trader! Welcome to CryptoSim. <br>
    We are a simulated Cryptocurrency Trading Platform. <br>
    We offer a risk-free environment for you to experiment with cryptocurrency investment strategies. <br> <br>
Please register or login to start your crypto-trading journey.</p>

{% endif %}


<div class="footer">
  <p>CryptoSim: "The Cryptocurrency Trading Simulator"</p>
</div>

{% endblock %}

code/cryptotradingsimulator/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'tradingplatform:index' %}">CryptoSim</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <style>
    a:hover{
    background-color:dimgray;
    color:white;
  }
  a:active{
    background-color:#000;
    color:white;
  }
  </style>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tradingplatform:trade' %}">Trade</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tradingplatform:portfolio' %}">Portfolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tradingplatform:following' %}">Following</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:logout' %}">Logout</a>
      </ul>
  </div>
    {% include 'balance.html' %}
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:register' %}">Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>